const Image = {
    Gambar1: require("../assets/HtmlDasar.jpg"),
    GambarTag1: require('../assets/Gambar.png'),
    GambarTag2: require('../assets/Gambar2.png'),
    GambarTag3: require('../assets/Gambar3.png'),
    GambarLink: require('../assets/GambarLink.png'),
    GambarLink2: require('../assets/GambarLink2.png'),
    GambarList: require('../assets/list.png'),
    GambarList1: require('../assets/list1.png'),
    GambarList2: require('../assets/list2.png'),
    GambarTable: require('../assets/table.png'),
    GambarTable2: require('../assets/table2.png'),
    GambarForm: require('../assets/formHTML.png'),
    GambarForm2: require('../assets/formHTML2.png'),
    GambarForm3: require('../assets/formHTML3.png'),
    GambarCss: require('../assets/CSS.png'),
    GambarCss2: require('../assets/CSS2.png'),
    GambarCss3: require('../assets/CSS3.png'),
    GambarCss4: require('../assets/CSS4.png'),
    GambarCss5: require('../assets/CSS6.png'),
    GambarCss6: require('../assets/CSS7.png'),
    GambarCss7: require('../assets/CSS8.png'),
    GambarCss8: require('../assets/CSS9.png'),
    GambarCss9: require('../assets/CSS10.png'),
    GambarCss10: require('../assets/CSS11.png'),
    GambarCss11: require('../assets/CSS12.png'),
    GambarCss12: require('../assets/CSS13.png'),
    GambarCss13: require('../assets/CSS14.png'),
    GambarCss14: require('../assets/CSS15.png'),
    GambarCss15: require('../assets/CSS16.png'),
    GambarCss16: require('../assets/CSS17.png'),
    GambarCss17: require('../assets/CSS18.png'),
    GambarCss18: require('../assets/CSS19.png'),
    GambarCss19: require('../assets/CSS20.png'),
    GambarCss20: require('../assets/CSS21.png'),
    GambarCss21: require('../assets/CSS22.png'),
    GambarCss22: require('../assets/CSS23.png'),
    GambarCss23: require('../assets/CSS24.png'),
    GambarCss24: require('../assets/CSS25.png'),
    GambarCss25: require('../assets/CSS26.png'),
    GambarCss26: require('../assets/CSS27.png'),
    GambarCss27: require('../assets/CSS28.png'),



}
export default Image;